### ISSUE TITLE
Double click > Jump to Annotation

### ISSUE THREAD

**Issue by N3C2L** [RyotaUshio/obsidian-pdf-plus#22]
If you double-click on a highlighted area in the PDF, it jumps to the correct location in the annotations file. However, the problem is that the tab with the note file does not get focused. Because the tab with the note file is not focused, you cannot immediately edit or delete the annotation. It would be better if, upon double-clicking on a highlight in the PDF, the note file in the other tab is focused so that you can edit or delete the annotation right away.

**Comment by N3C2L** [comment]
The double click should work like this function: In the PDF++ Settings: "Action when hovering over highlighted text" set to "open backlink".

**Comment by RyotaUshio** [comment]
Thanks, the "Don't move focus to markdown view after opening a backlink" option was supposed to work for this, but it was not working. It has been fixed and released as [0.27.1](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.27.1).

**Comment by N3C2L** [comment]
I still have a problem with it: 
How to reproduce:
1. Create 5 links (copy as quote format) with a large text selection (1 page for example) + insert them in the annotations file.
2. In the annotation file scroll to the bottom and write some random words.
3. Double click on the first highlighted link in the PDF viewer.
4. In the annotation file this link will be focused, but if you click now in the text selection of this link (in the annotation file), the focus jumps down to bottom (where you typed the random words).
