### ISSUE TITLE
[Bug] Location for dummy pdf's not recognized or saved

### ISSUE THREAD

**Issue by juanreppucci** [RyotaUshio/obsidian-pdf-plus#395]
### Steps to reproduce

Go to settings/PDF++/Dummy pdf for externa files
in "default location for dummy pdf files" select "in the folder specified below"
in "Dummy forder path" put a name of an already creted folder or choose it from dopdown
in "Modifier key to create a dummy PDF file on drag & drop" choose "shift"

### Expected behavior

When you drag a pdf to the vault it will creat a dummy file stored in the selected folder

### Actual behavior

It creates a copy of the full pdf (not dummy pdf) at the default Obsidian folder. 
It seems that the cange in settings do not change. 
This happened in a minimal vault. In my actual vault I have a folder name by default (Dummy pdfs) when I change it goes back to it, but saves the pdf in obsidian Default location for new attachments (not the folder I spacified or the one is on the PDF++ settings).

It was working well before. 

### Screen recordings or screenshots

![Image](https://github.com/user-attachments/assets/405a7f69-e972-48ec-a954-4256d53a6d8b)

#### Obsidian debug info

- Obsidian version: 1.8.7
- Installer version: 1.6.3
- Operating system: Windows 10 Home 10.0.19045
- Use [[Wikilinks]]: false
- Base color scheme: dark
- PDF "Adapt to theme": false
- Community theme: none
- Snippets enabled: 0
- Plugins installed: 1
- Plugins enabled: 1
    - PDF++ v0.40.24

#### PDF++ debug info

```
{"settings":{"displayTextFormats":[{"name":"Title & page","template":"{{file.basename}}, p.{{pageLabel}}"},{"name":"Page","template":"p.{{pageLabel}}"},{"name":"Text","template":"{{text}}"},{"name":"Emoji","template":"📖"},{"name":"None","template":""}],"defaultDisplayTextFormatIndex":0,"syncDisplayTextFormat":true,"syncDefaultDisplayTextFormat":false,"copyCommands":[{"name":"Quote","template":"> ({{linkWithDisplay}})\n> {{selection}}\n"},{"name":"Link","template":"{{linkWithDisplay}}"},{"name":"Embed","template":"!{{link}}"},{"name":"Callout","template":"> [!{{calloutType}}|{{color}}] {{linkWithDisplay}}\n> {{text}}\n"},{"name":"Quote in callout","template":"> [!{{calloutType}}|{{color}}] {{linkWithDisplay}}\n> > {{text}}\n> \n> "}],"useAnotherCopyTemplateWhenNoSelection":false,"copyTemplateWhenNoSelection":"{{linkToPageWithDisplay}}","trimSelectionEmbed":false,"embedMargin":50,"noSidebarInEmbed":true,"noSpreadModeInEmbed":true,"embedUnscrollable":false,"singleTabForSinglePDF":true,"highlightExistingTab":false,"existingTabHighlightOpacity":0.5,"existingTabHighlightDuration":0.75,"paneTypeForFirstPDFLeaf":"left","openLinkNextToExistingPDFTab":true,"openPDFWithDefaultApp":false,"openPDFWithDefaultAppAndObsidian":true,"focusObsidianAfterOpenPDFWithDefaultApp":true,"syncWithDefaultApp":false,"dontActivateAfterOpenPDF":true,"dontActivateAfterOpenMD":true,"highlightDuration":0.75,"noTextHighlightsInEmbed":false,"noAnnotationHighlightsInEmbed":true,"persistentTextHighlightsInEmbed":true,"persistentAnnotationHighlightsInEmbed":false,"highlightBacklinks":true,"selectionBacklinkVisualizeStyle":"highlight","dblclickEmbedToOpenLink":true,"highlightBacklinksPane":true,"highlightOnHoverBacklinkPane":true,"backlinkHoverColor":"","colors":{"Yellow":"#ffd000","Red":"#ea5252","Note":"#086ddd","Important":"#bb61e5"},"defaultColor":"","defaultColorPaletteItemIndex":0,"syncColorPaletteItem":true,"syncDefaultColorPaletteItem":false,"colorPaletteInToolbar":true,"noColorButtonInColorPalette":true,"colorPaletteInEmbedToolbar":false,"quietColorPaletteTooltip":false,"showStatusInToolbar":true,"highlightColorSpecifiedOnly":false,"doubleClickHighlightToOpenBacklink":true,"hoverHighlightAction":"preview","paneTypeForFirstMDLeaf":"right","singleMDLeafInSidebar":true,"alwaysUseSidebar":true,"ignoreExistingMarkdownTabIn":[],"defaultColorPaletteActionIndex":4,"syncColorPaletteAction":true,"syncDefaultColorPaletteAction":false,"proxyMDProperty":"PDF","hoverPDFLinkToOpen":false,"ignoreHeightParamInPopoverPreview":true,"filterBacklinksByPageDefault":true,"showBacklinkToPage":true,"enableHoverPDFInternalLink":true,"recordPDFInternalLinkHistory":true,"alwaysRecordHistory":true,"renderMarkdownInStickyNote":false,"enablePDFEdit":false,"author":"","writeHighlightToFileOpacity":0.2,"defaultWriteFileToggle":false,"syncWriteFileToggle":true,"syncDefaultWriteFileToggle":false,"enableAnnotationDeletion":true,"warnEveryAnnotationDelete":false,"warnBacklinkedAnnotationDelete":true,"enableAnnotationContentEdit":true,"enableEditEncryptedPDF":false,"pdfLinkColor":"#04a802","pdfLinkBorder":false,"replaceContextMenu":true,"showContextMenuOnMouseUpIf":"Mod","contextMenuConfig":[{"id":"action","visible":true},{"id":"selection","visible":true},{"id":"write-file","visible":true},{"id":"annotation","visible":true},{"id":"modify-annotation","visible":true},{"id":"link","visible":true},{"id":"text","visible":true},{"id":"search","visible":true},{"id":"speech","visible":true},{"id":"page","visible":true},{"id":"settings","visible":true}],"selectionProductMenuConfig":["color","copy-format","display"],"writeFileProductMenuConfig":["color","copy-format","display"],"annotationProductMenuConfig":["copy-format","display"],"updateColorPaletteStateFromContextMenu":true,"mobileCopyAction":"pdf-plus","showContextMenuOnTablet":false,"executeBuiltinCommandForOutline":true,"executeBuiltinCommandForZoom":true,"executeFontSizeAdjusterCommand":true,"closeSidebarWithShowCommandIfExist":true,"autoHidePDFSidebar":false,"defaultSidebarView":1,"outlineDrag":true,"outlineContextMenu":true,"outlineLinkDisplayTextFormat":"{{file.basename}}, {{text}}","outlineLinkCopyFormat":"{{linkWithDisplay}}","recordHistoryOnOutlineClick":true,"popoverPreviewOnOutlineHover":true,"thumbnailDrag":true,"thumbnailContextMenu":true,"thumbnailLinkDisplayTextFormat":"{{file.basename}}, p.{{pageLabel}}","thumbnailLinkCopyFormat":"{{linkWithDisplay}}","recordHistoryOnThumbnailClick":true,"popoverPreviewOnThumbnailHover":true,"annotationPopupDrag":true,"showAnnotationPopupOnHover":true,"useCallout":true,"calloutType":"PDF","calloutIcon":"highlighter","highlightBacklinksInEmbed":false,"highlightBacklinksInHoverPopover":false,"highlightBacklinksInCanvas":true,"clickPDFInternalLinkWithModifierKey":true,"clickOutlineItemWithModifierKey":true,"clickThumbnailWithModifierKey":true,"focusEditorAfterAutoPaste":true,"clearSelectionAfterAutoPaste":true,"respectCursorPositionWhenAutoPaste":true,"blankLineAboveAppendedContent":true,"autoCopy":false,"autoFocus":false,"autoPaste":false,"autoFocusTarget":"last-active-and-open-then-last-paste","autoPasteTarget":"last-active-and-open-then-last-paste","openAutoFocusTargetIfNotOpened":true,"howToOpenAutoFocusTargetIfNotOpened":"right","closeHoverEditorWhenLostFocus":true,"closeSidebarWhenLostFocus":false,"openAutoFocusTargetInEditingView":true,"executeCommandWhenTargetNotIdentified":true,"commandToExecuteWhenTargetNotIdentified":"switcher:open","autoPasteTargetDialogTimeoutSec":20,"autoCopyToggleRibbonIcon":true,"autoCopyIconName":"highlighter","autoFocusToggleRibbonIcon":true,"autoFocusIconName":"zap","autoPasteToggleRibbonIcon":true,"autoPasteIconName":"clipboard-paste","viewSyncFollowPageNumber":true,"viewSyncPageDebounceInterval":0.3,"openAfterExtractPages":true,"howToOpenExtractedPDF":"tab","warnEveryPageDelete":false,"warnBacklinkedPageDelete":true,"extractPageInPlace":false,"askExtractPageInPlace":true,"pageLabelUpdateWhenInsertPage":"keep","pageLabelUpdateWhenDeletePage":"keep","pageLabelUpdateWhenExtractPage":"keep","askPageLabelUpdateWhenInsertPage":true,"askPageLabelUpdateWhenDeletePage":true,"askPageLabelUpdateWhenExtractPage":true,"copyOutlineAsListFormat":"{{linkWithDisplay}}","copyOutlineAsListDisplayTextFormat":"{{text}}","copyOutlineAsHeadingsFormat":"{{text}}\n\n{{linkWithDisplay}}","copyOutlineAsHeadingsDisplayTextFormat":"p.{{pageLabel}}","copyOutlineAsHeadingsMinLevel":2,"newFileNameFormat":"","newFileTemplatePath":"","newPDFLocation":"current","newPDFFolderPath":"","rectEmbedStaticImage":false,"rectImageFormat":"file","rectImageExtension":"webp","zoomToFitRect":false,"rectEmbedResolution":100,"includeColorWhenCopyingRectLink":true,"backlinkIconSize":50,"showBacklinkIconForSelection":false,"showBacklinkIconForAnnotation":false,"showBacklinkIconForOffset":true,"showBacklinkIconForRect":false,"showBoundingRectForBacklinkedAnnot":false,"hideReplyAnnotation":false,"searchLinkHighlightAll":"true","searchLinkCaseSensitive":"true","searchLinkMatchDiacritics":"default","searchLinkEntireWord":"false","dontFitWidthWhenOpenPDFLink":true,"preserveCurrentLeftOffsetWhenOpenPDFLink":false,"defaultZoomValue":"page-width","scrollModeOnLoad":0,"spreadModeOnLoad":0,"usePageUpAndPageDown":true,"hoverableDropdownMenuInToolbar":true,"zoomLevelInputBoxInToolbar":true,"popoverPreviewOnExternalLinkHover":true,"actionOnCitationHover":"pdf-plus-bib-popover","anystylePath":"","enableBibInEmbed":false,"enableBibInHoverPopover":false,"enableBibInCanvas":true,"citationIdPatterns":"^cite.\n^bib\\d+$","copyAsSingleLine":true,"removeWhitespaceBetweenCJChars":true,"dummyFileFolderPath":"Dummy PDFs","externalURIPatterns":[".*\\.pdf$","https://arxiv.org/pdf/.*"],"modifierToDropExternalPDFToCreateDummy":["Shift"],"vim":false,"vimrcPath":"","vimVisualMotion":true,"vimScrollSize":40,"vimLargerScrollSizeWhenZoomIn":true,"vimContinuousScrollSpeed":1.2,"vimSmoothScroll":true,"vimHlsearch":true,"vimIncsearch":true,"enableVimInContextMenu":true,"enableVimOutlineMode":true,"vimSmoothOutlineMode":true,"vimHintChars":"hjklasdfgyuiopqwertnmzxcvb","vimHintArgs":"all","PATH":""},"styleSettings":null,"styleSheet":".pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"yellow\"],\n.pdf-embed[data-highlight-color=\"yellow\"] .textLayer .mod-focused {\n    --pdf-plus-color: #ffd000;\n    --pdf-plus-backlink-icon-color: #ffd000;\n    --pdf-plus-rect-color: #ffd000;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"red\"],\n.pdf-embed[data-highlight-color=\"red\"] .textLayer .mod-focused {\n    --pdf-plus-color: #ea5252;\n    --pdf-plus-backlink-icon-color: #ea5252;\n    --pdf-plus-rect-color: #ea5252;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"note\"],\n.pdf-embed[data-highlight-color=\"note\"] .textLayer .mod-focused {\n    --pdf-plus-color: #086ddd;\n    --pdf-plus-backlink-icon-color: #086ddd;\n    --pdf-plus-rect-color: #086ddd;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight)[data-highlight-color=\"important\"],\n.pdf-embed[data-highlight-color=\"important\"] .textLayer .mod-focused {\n    --pdf-plus-color: #bb61e5;\n    --pdf-plus-backlink-icon-color: #bb61e5;\n    --pdf-plus-rect-color: #bb61e5;\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink:not(.hovered-highlight) {\n    --pdf-plus-color: rgb(var(--text-highlight-bg-rgb));\n    --pdf-plus-backlink-icon-color: rgb(var(--text-highlight-bg-rgb));\n    --pdf-plus-rect-color: rgb(var(--text-highlight-bg-rgb));\n}\n.pdf-plus-backlink-highlight-layer .pdf-plus-backlink.hovered-highlight {\n\t--pdf-plus-color: green;\n\t--pdf-plus-backlink-icon-color: green;\n   --pdf-plus-rect-color: green;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"yellow\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #ffd000;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"red\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #ea5252;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"note\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #086ddd;\n}\n.pdf-plus-color-palette-item[data-highlight-color=\"important\"] > .pdf-plus-color-palette-item-inner {\n    background-color: #bb61e5;\n}\n.pdf-plus-color-palette-item:not([data-highlight-color]) > .pdf-plus-color-palette-item-inner {\n    background-color: transparent;\n}\n.workspace-leaf.pdf-plus-link-opened.is-highlighted::before {\n\topacity: 0.5;\n}\nbody {\n    --pdf-plus-yellow-rgb: 255, 208, 0\n}\nbody {\n    --pdf-plus-red-rgb: 234, 82, 82\n}\nbody {\n    --pdf-plus-note-rgb: 8, 109, 221\n}\nbody {\n    --pdf-plus-important-rgb: 187, 97, 229\n}\nbody {\n    --pdf-plus-default-color-rgb: var(--text-highlight-bg-rgb)\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"yellow\"] {\n\t--callout-color: var(--pdf-plus-yellow-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"red\"] {\n\t--callout-color: var(--pdf-plus-red-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"note\"] {\n\t--callout-color: var(--pdf-plus-note-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"][data-callout-metadata=\"important\"] {\n\t--callout-color: var(--pdf-plus-important-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"] {\n\t--callout-color: var(--pdf-plus-default-color-rgb);\n   background-color: rgba(var(--callout-color), var(--pdf-plus-highlight-opacity, 0.2))\n}\n.callout[data-callout=\"pdf\"] {\n   --callout-icon: lucide-highlighter;\n}"}
```

**Comment by RyotaUshio** [comment]
Thanks! In "steps to reproduce", you said

> in "Dummy forder path" put a name of an already creted folder or choose it from dopdown

However, both in your screenshot and in your debug info, it seems that you didn't enter any value in the box. In the screenshot, it shows the example placeholder "Dummy PDFs" which means the value is empty. "Dummy PDFs" is just placeholder and not the default value (sorry it might be confusing).

In this case, since the folder path is not provided by the user, PDF++ uses Obsidian's default attachment folder (specified in Settings > Files and links > Default location for new attachments), which is an intended behavior.

Does it happen when you actually put an existing folder path in the box?

>  In my actual vault I have a folder name by default (Dummy pdfs) when I change it goes back to it

Sorry, I also couldn't understand this part.

**Comment by RyotaUshio** [comment]
Thanks, I've noticed something is not working properly in the folder suggester. I will release a fix today. Let me know if the bug persists in the next version.

**Comment by RyotaUshio** [comment]
@juanreppucci The fix has been released in [0.40.25](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.40.25). How about now?

**Comment by juanreppucci** [comment]
Hello, thanks for your reply and help!
Sadly is still the same, 
I think the problem is that it is not saving the settings on that section. I just made a video, just to test first another setting "Annotation author" and then the specified folder for dummy pdf. You'll see that the changes on the folder were not saved. 
For some reason I cannot upload the video here, but you can watch it here https://youtu.be/UKl_uxivLvY
I hope this helps 
Thanks a lot
bests

**Comment by RyotaUshio** [comment]
Thank you, I found a silly mistake in the code and now the setting tab should update properly in [0.40.26](https://github.com/RyotaUshio/obsidian-pdf-plus/releases/tag/0.40.26).

**Comment by juanreppucci** [comment]
Hello @RyotaUshio I just tested it. Now it saves the settings, but still when I try to create the dummy pdf (by dragging holding shift key), it makes a copy of the pdf in the obsidian default folder. Not only is it in a different folder than specified, but it also creates a copy (not a dummy pdf). 
here is a screenshot of the settings

![Image](https://github.com/user-attachments/assets/cc74bf13-0c79-4016-89c8-692822bbf028)

**Comment by RyotaUshio** [comment]
@juanreppucci Thanks. At this point, I think the problem is Obsidian seem not to be recognizing that you're pressing Shift when you drag & drop. And it's probably because your **installer version** (not the app version) is out-of-date.

In my test, if I used the [v1.6.3 installer](https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.6.3), I was able to produce the bug. However, if I used the latest v1.8.7 installer, the Shift key was recognized properly and I was able to create dummy files successfully.
 
Try downloading the latest installer from https://obsidian.md/download and re-installing Obsidian.

**Comment by RyotaUshio** [comment]
After further testing, v1.6.3 installer fails to recognize Shift and to create dummy files while all installers newer than it (v1.6.5 or above) succeed. Probably the specific Electron version bundled with the 1.6.3 installer had a bug.
